#!/bin/bash
#Website= khk.ee

#Defining the variables

host=$1
firstport=$2
lastport=$3

#checking the ports to see if they are open

function portscan

{
for ((counter=$firstport; counter<=$lastport; counter++))
do
  (echo >/dev/tcp/$host/$counter) > /dev/null 2>$1 && echo "$counter
open"
done
}

#run the function
portscan

