#!/bin/bash
#
# Prooov
clear
#
echo -n "Sisesta veebileht: "
read veebileht
nmap="nmap --open $veebileht"
$nmap
# Kysime, kas kasutaja soovib tulemusi txt failina salvestada?
read salvestada
echo "Kas soovite faili .txt failina salvestada?"
read -p "Valige (Y/N)"
if [ "$Valige" = "Y" ]; then
 read "./scan2.sh > $veebileht.txt"
 touch $nmap > $veebileht.txt
 echo "Fail on salvestatud."
exit
fi
