#!/bin/bash
# Veebilehe avatud portide tuvastamine
clear
#
echo -n "Sisesta veebileht: "
read veebileht
nmap="nmap --open $veebileht"
$nmap | tee -a $veebileht.txt
# Utleme, et fail on salvestatud
echo "Fail on salvestatud $veebileht.txt kujul."
# skripti lopp
exit


